### ISSUE TITLE
Warning: a promise was created in a handler at ../../loopback-boot/lib/executor.js:311:9

### ISSUE THREAD

**Issue by beeman** [colmena/colmena#265]
```
(node:93409) Warning: a promise was created in a handler at Users/beeman/workspace/colmena/colmena/apps/api/node_modules/loopback-boot/lib/executor.js:311:9 but was not returned from it, see http://goo.gl/rRqMUw\n    at new Promise (/Users/beeman/workspace/colmena/colmena/apps/api/node_modules/bluebird/js/release/promise.js:79:10)
```

This error is caused by the code in the script `apps/api/server/boot/10-init-settings.js`

**Comment by beeman** [comment]
Closing, will be fixed when #273 lands
